In [1]:
import numpy as np
n=[1,2,3,4,5]
n=np.array(n)
print("1 dim. array:",n)

1 dim. array: [1 2 3 4 5]


In [40]:
n1=[1,2,3,4,5],["shital","sangit"]
n1=np.array(n1)
print("2 dim. array:",n1)

2 dim. array: [list([1, 2, 3, 4, 5]) list(['shital', 'sangit'])]


C:\Users\uspat\AppData\Local\Temp\ipykernel_1372\844812702.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  n1=np.array(n1)


In [6]:
eyemat=np.eye(4)
print("one cross diagonal\n\n",eyemat)

one cross diagonal

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
random_pr=np.random.randint(0,100,10) #select 10 numbers from 0 to 100
print("random numbers from 0 to 100:\n",random_pr)


random numbers from 0 to 100:
 [99 16 98 45 57 63 56 97 64 56 27 45 58 26 78 11 56 97 97 71]


In [20]:
names=np.array(["shital","gitisha","kavish","sangit"])
print("Last element of the array \n",names[-1])
print("\n to print reverse order of array\n",names[::-1])

Last element of the array 
 sangit

 to print reverse order of array
 ['sangit' 'kavish' 'gitisha' 'shital']


In [23]:
numbers=np.array([[1,2,3],[4,5,6],[5,7,8]])
print("second row,third element",numbers[1][2])
print("for print array\n",numbers)

second row,third element 6
for print array
 [[1 2 3]
 [4 5 6]
 [5 7 8]]


In [22]:
numbers=np.arange(1,26).reshape(5,5)
print("Numbers inserted\n\n",numbers)

Numbers inserted

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [25]:
numbers=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
numbers[numbers%2==0]=10
print("replace 10 on even number\t",numbers)

replace 10 on even number	 [10  1 10  3 10  5 10  7 10  9 10 11 10 13 10 15]


In [31]:
numbers=np.arange(10)
print(numbers)
print("reshape 1 dimension to 2 dimension\n")
numbers.reshape(2,-1)

[0 1 2 3 4 5 6 7 8 9]
reshape 1 dimension to 2 dimension



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
x=np.array([36,10,6,45,30,2])
y=np.array([36,85,10,2,7,30])
print("common ele in two array")
np.intersect1d(x,y)

common ele in two array


array([ 2, 10, 30, 36])

In [39]:
numbers=np.arange(10)
print(numbers)
numbers[(numbers>=3) & (numbers <=6)]

[0 1 2 3 4 5 6 7 8 9]


array([3, 4, 5, 6])

In [41]:
import pandas as pd
import numpy as np
sample_dict={"x":1,"y":2,"z":3}
the_series=pd.Series(sample_dict)
print(the_series)

x    1
y    2
z    3
dtype: int64


In [44]:
sample_series=pd.Series(list('123456789'))
sample_series.name='numbers'
sample_series.head()

0    1
1    2
2    3
3    4
4    5
Name: numbers, dtype: object

In [54]:
first_series=pd.Series([1,2,3,4,6])
sec_series=pd.Series([5,6,7,8,4])
first_series[~first_series.isin(sec_series)]#the number which is in sec series not in first series means common number

0    1
1    2
2    3
dtype: int64

In [59]:
sample_series=pd.Series(np.random.randint(1,30,36))
data_frame=pd.DataFrame(sample_series.values.reshape(6,6))
print(data_frame)

    0   1   2   3   4   5
0  13  10  21  13  10  14
1  17   9   8   5  25   4
2  20  22  16   9  28  22
3   8  29   2  28   4  10
4  12  22  26   6  11   1
5   5  25  29  13  27  15
